#!/bin/bash
# run this file using bash trainSLURMwrapper

filename=arABcx2D

# select k1=0,k2=0 to remove filename tag run_k 
h1=1 ; h2=30
k1=0 ; k2=0

echo "fitting model ${filename}..."

idx=-1
for h in $(seq $h1 $h2); do 
	for k in $(seq $k1 $k2); do
		let idx++	
		echo "xdim=${h}, run=${k}" 
	done
done

asz=$(($idx+1))

echo "job array size = ${asz}"

export filename h1 h2 k1 k2 

sbatch --array=0-$idx --job-name=${filename} trainSLURM
